### ISSUE TITLE
use public url for gotools-data

### ISSUE THREAD

**Issue by fgfuchs** [SINTEF-Geometry/GoTools#168]
Recursive cloning fails. Please use the public url, i.e., url = https://github.com/SINTEF-Geometry/GoTools-Data.git, for the submodule
[submodule "gotools-data"]
    path = gotools-data
    url = https://github.com/SINTEF-Geometry/GoTools-Data.git

instead of git@github.com:SINTEF-Geometry/GoTools-Data.git

**Comment by sbriseid** [comment]
Thanks for the bug report and the proposed fix, everything is ok now!
