### ISSUE TITLE
Missing dependencies installation instructions

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF-Geometry/GoTools#179]
GoTools and its submodules have the following libraries tagged as REQUIRED (in its cmake files), but they do not appear in any INSTALLATION or README files

* PugiXML
* OpenMP
* JsonCpp
* OpenGL
* Qt4
* Qt5
* GLUT

**Comment by sbriseid** [comment]
Thanks for the feedback! Qt4, OpenGL & GLUT are required for viewlib only, as mentioned in the README file. Qt5 support was recently added, I'll add that to the README file. OpenMP is disabled by default, but it should nonetheless be mentioned. PugiXML & JsonCpp are enlisted in the wiki, but the user should of course not have to rely on external documentation. I'll clean up the mess.
