### ISSUE TITLE
cmake so many error. It seems that many files is missing.

### ISSUE THREAD

**Issue by ztdepztdep** [SINTEF-Geometry/GoTools#257]
CMake Error at gotools-core/CMakeLists.txt:80 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/gotools-core/../gotools-data/gotools-core/data".

CMake Error at gotools-core/CMakeLists.txt:82 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/gotools-core/../gotools-data/gotools-core/examples/data".

CMake Error at trivariate/CMakeLists.txt:63 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/trivariate/../gotools-data/trivariate/examples/data".

CMake Error at compositemodel/CMakeLists.txt:107 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/compositemodel/../gotools-data/compositemodel/data".

CMake Error at compositemodel/CMakeLists.txt:109 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/compositemodel/../gotools-data/compositemodel/examples/data".

CMake Error at trivariatemodel/CMakeLists.txt:91 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/trivariatemodel/../gotools-data/trivariatemodel/data".

CMake Error at trivariatemodel/CMakeLists.txt:93 (FILE):
  FILE COPY cannot find
  "/home/ztdep/Downloads/GoTools/trivariatemodel/../gotools-data/trivariatemodel/examples/data".

**Comment by sbriseid** [comment]
Hi, thanks for the feedback!

This is the result of not initializing the submodules. From inside the source directory do:
$ git submodule update --init --recursive
