### ISSUE TITLE
STEP importer imssing

### ISSUE THREAD

**Issue by happydpc** [SINTEF-Geometry/GoTools#287]
I found that step importer was been an option in the cmake file. But the dir not exist in the repo.

**Comment by sbriseid** [comment]
Step is unfortunately not supported by GoTools. I could not find any reference to step in the CMakeLists.txt files. If it ever was included it was not the intention. Please enlighten me and I'll remove the option if it still exists.

We do however support IGES (through the module igeslib).

STEP is supported in our step_reader module which requires a license.

**Comment by happydpc** [comment]
Oh, I see, that's cmake log history. I wonder now GoTools can be used to implement how many features that opencascade can do? Opencascade is so slow to use, I want to try an alternative library.
