### ISSUE TITLE
Run examples error

### ISSUE THREAD

**Issue by happydpc** [SINTEF-Geometry/GoTools#288]
![微信图片_20191030011558](https://user-images.githubusercontent.com/771776/67791707-e71beb00-fab2-11e9-866a-965e6b4b4c57.png) 
![image](https://user-images.githubusercontent.com/771776/67791790-087cd700-fab3-11e9-9a94-c23e3dfc7774.png)

**Comment by sbriseid** [comment]
That is strange. It runs perfectly on linux,. but fails miserably on windows. I'll look into it.

**Comment by sbriseid** [comment]
Thanks for the bug report! The else statement was missing a test. The bug was present in linux as well, but was swept under the carpet. I'll make a fix right away. Keeping the issue open until master is updated with the fix.
