### ISSUE TITLE
Test #17 failed

### ISSUE THREAD

**Issue by GBZH** [SINTEF-Geometry/GoTools#302]
Hello,

First of all, thanks a lot for this impressive software !
I managed to compile GoTools and ran the tests. Except for one of them, everything went fine. Do you have any clue for this failure ?
$> make test
Running tests...
Test project /home/quemener/local/SINTEF/build_GoTools
      Start  1: BoundedSurfaceTest
 1/20 Test  #1: BoundedSurfaceTest ...............   Passed    0.01 sec
      Start  2: CurveCreatorsTest
 2/20 Test  #2: CurveCreatorsTest ................   Passed    0.04 sec
      Start  3: CurveOnSurfaceTest
 3/20 Test  #3: CurveOnSurfaceTest ...............   Passed    0.01 sec
      Start  4: ElementaryObjectsTest
 4/20 Test  #4: ElementaryObjectsTest ............   Passed    0.01 sec
      Start  5: GoToolsTest
 5/20 Test  #5: GoToolsTest ......................   Passed    0.01 sec
      Start  6: LoopUtilsTest
 6/20 Test  #6: LoopUtilsTest ....................   Passed    0.01 sec
      Start  7: OffsetSurfaceTest
 7/20 Test  #7: OffsetSurfaceTest ................   Passed    0.01 sec
      Start  8: SphereTest
 8/20 Test  #8: SphereTest .......................   Passed    0.01 sec
      Start  9: SplineCurveTest
 9/20 Test  #9: SplineCurveTest ..................   Passed    0.00 sec
      Start 10: SplineSurfaceTest
10/20 Test #10: SplineSurfaceTest ................   Passed    0.00 sec
      Start 11: fixInvalidBoundedSurfaceTest
11/20 Test #11: fixInvalidBoundedSurfaceTest .....   Passed    0.01 sec
      Start 12: FaceAdjacencyTest
12/20 Test #12: FaceAdjacencyTest ................   Passed    0.00 sec
      Start 13: CompositeModelFileHandlerTest
13/20 Test #13: CompositeModelFileHandlerTest ....   Passed    0.00 sec
      Start 14: ExampleTest
14/20 Test #14: ExampleTest ......................   Passed    0.00 sec
      Start 15: HermiteApprEvalSurfTest
15/20 Test #15: HermiteApprEvalSurfTest ..........   Passed    0.00 sec
      Start 16: ftEdgeTest
16/20 Test #16: ftEdgeTest .......................   Passed    0.01 sec
      Start 17: offsetSurfaceSetTest
17/20 Test #17: offsetSurfaceSetTest .............***Failed    0.00 sec
      Start 18: splitFaceSetTest
18/20 Test #18: splitFaceSetTest .................   Passed    2.75 sec
      Start 19: solid2trivariateTest
19/20 Test #19: solid2trivariateTest .............   Passed   16.83 sec
      Start 20: LRSplineSurfaceTest
20/20 Test #20: LRSplineSurfaceTest ..............   Passed    0.01 sec

95% tests passed, 1 tests failed out of 20

Label Time Summary:
test/acceptance    =  19.59 sec*proc (3 tests)
test/unit          =   0.15 sec*proc (17 tests)

Total Test time (real) =  19.77 sec

The following tests FAILED:
	 17 - offsetSurfaceSetTest (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8

Thanks a lot for any help.
Best regards,

   Gilles

**Comment by sbriseid** [comment]
Thanks for the kind words!

And thanks for pointing out this error! The reason for the failed test is that all the data files for this particular test are part of our private data repository. Resulting in an "Input file not found" error.

I'll create a fix for this issue as soon as possible.

Best regards,
Sverre

**Comment by sbriseid** [comment]
Butterfingers caused me to close this issue a bit too early ... :) But now it should be resolved. Pull down the latest master branch and all tests should run without failure.

Thanks again for pointing out the error!
