### ISSUE TITLE
Compiling a simple code

### ISSUE THREAD

**Issue by GBZH** [SINTEF-Geometry/GoTools#303]
Hello,

Even if I was able to compile GoTools and to run the tests, I am currently not able to compile a simple code as for instance a modified version of  GoTools/gotools-core/examples/circle.C. Would it be possible to have somewhere a single target Makefile available for such a purpose instead of the whole cmake / make myriads of files used to compile the whole library ?

Thanks a lot for any help.
Best regards,

  Gilles

**Comment by VibekeSkytt** [comment]
To compile one single application file or example file you can write make application name, for instance make Circle. You must run cmake first.

Vibeke

**Comment by GBZH** [comment]
Dear Vibeke, 

Thanks a lot for your answer. 
My problem is not to compile a file which is already in the distribution (in any app or examples folder), but rather to compile a file that I have for instance copied and modified or created in my home directory. 
Up to now, I was not able to compile one. I have written the following simple bash script (named run) to compile and run a given code: 

#!/bin/bash 

rm *.o *~ 

filename=$1 
echo $filename 
# Tests if input file has an extension and if yes, removes it 
case `basename "$filename"` in 
*.* ) 
echo has an extension and is now removed 
file="${filename%%.*}" 
;; 
* ) 
echo does not have an extension 
file=$filename 
;; 
esac 

cppfile="$file.C" 
ofile="$file.o" 

g++ -c -I/usr/local/include $cppfile 
g++ $ofile -L/usr/local/lib -lttl -lnewmat -lsisl -lviewlib -lGoToolsCore -lGoTopology -lGoImplicitization -lparametrization -lGoTrivariate -lGoIgeslib -lGoLRspline2D -lGoIntersections -lGoCompositeModel -lGoQualityModule -lGoTrivariateModel -lGoIsogeometricModel -lstdc++ -lm 
-o $file 
echo 'Program compiled : '${file} 
$file 

With GotTools include files installed in : 
/usr/local/include $> ls 
boost GoTools newmat sisl-copyright.h sisl.h sislP.h spdlog ttl 
and the libs .a files in /usr/local/lib 
I obtain the following errors which I have not managed to resolve up to now when I tried to compile the file circle.C located in my home directory : 

mer. août 19 - 16:21:32 : quemener@pclin1 : ~ $> run circle.C 
circle.C 
has an extension and is now removed 
/usr/local/lib/libGoToolsCore.a(Circle.C.o): In function `Go::Circle::createNonRationalSpline(double) const': 
Circle.C:(.text+0x2d9d): undefined reference to `s1303' 
Circle.C:(.text+0x2e74): undefined reference to `freeCurve' 
/usr/local/lib/libGoToolsCore.a(BoundedUtils.C.o): In function `Go::BoundedUtils::intersectWithPlane(std::shared_ptr<Go::ParamSurface>&, Go::Point, Go::Point, double)': 
BoundedUtils.C:(.text+0xdf17): undefined reference to `s1851' 
BoundedUtils.C:(.text+0xe0d0): undefined reference to `s1314' 
BoundedUtils.C:(.text+0xe626): undefined reference to `freeIntcrvlist' 
BoundedUtils.C:(.text+0xe635): undefined reference to `freeSurf' 
/usr/local/lib/libGoToolsCore.a(BoundedUtils.C.o): In function `Go::BoundedUtils::intersectWithLine(std::shared_ptr<Go::ParamSurface>&, Go::Point, Go::Point, double)': 
BoundedUtils.C:(.text+0xe9d3): undefined reference to `s1856' 
BoundedUtils.C:(.text+0xed96): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0xedd4): undefined reference to `freeIntcrvlist' 
/usr/local/lib/libGoToolsCore.a(BoundedUtils.C.o): In function `Go::BoundedUtils::intersectWithCylinder(std::shared_ptr<Go::ParamSurface>&, Go::Point, Go::Point, double, double)': 
BoundedUtils.C:(.text+0xf13e): undefined reference to `s1853' 
BoundedUtils.C:(.text+0xf301): undefined reference to `s1316' 
BoundedUtils.C:(.text+0xf857): undefined reference to `freeIntcrvlist' 
BoundedUtils.C:(.text+0xf866): undefined reference to `freeSurf' 
/usr/local/lib/libGoToolsCore.a(BoundedUtils.C.o): In function `Go::BoundedUtils::getIntersectionCurve(std::shared_ptr<Go::ParamSurface>&, std::shared_ptr<Go::ParamSurface>&, std::vector<std::shared_ptr<Go::CurveOnSurface>, std::allocator<std::shared_ptr<Go::CurveOnSurface> > >&, std::vector<std::shared_ptr<Go::CurveOnSurface>, std::allocator<std::shared_ptr<Go::CurveOnSurface> > >&, double)': 
BoundedUtils.C:(.text+0xfeaf): undefined reference to `s1859' 
BoundedUtils.C:(.text+0xfeda): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0xfef3): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0xff4c): undefined reference to `freeIntcrvlist' 
BoundedUtils.C:(.text+0x102c6): undefined reference to `s1859' 
BoundedUtils.C:(.text+0x102f1): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0x1030a): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0x10363): undefined reference to `freeIntcrvlist' 
BoundedUtils.C:(.text+0x1042b): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0x10444): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0x11572): undefined reference to `s1310' 
BoundedUtils.C:(.text+0x11814): undefined reference to `s1310' 
BoundedUtils.C:(.text+0x12992): undefined reference to `s1785' 
BoundedUtils.C:(.text+0x129a1): undefined reference to `freeCurve' 
BoundedUtils.C:(.text+0x135bb): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0x135d4): undefined reference to `freeSurf' 
BoundedUtils.C:(.text+0x13621): undefined reference to `freeIntcrvlist' 
/usr/local/lib/libGoToolsCore.a(SISLconversion.C.o): In function `Go::Curve2SISL(Go::SplineCurve const&, bool)': 
SISLconversion.C:(.text+0x1a0): undefined reference to `newCurve' 
/usr/local/lib/libGoToolsCore.a(SISLconversion.C.o): In function `Go::Curve2SISL_rat(Go::SplineCurve const&)': 
SISLconversion.C:(.text+0x2a4): undefined reference to `newCurve' 
SISLconversion.C:(.text+0x467): undefined reference to `newCurve' 
/usr/local/lib/libGoToolsCore.a(SISLconversion.C.o): In function `Go::GoSurf2SISL(Go::SplineSurface const&, bool)': 
SISLconversion.C:(.text+0x781): undefined reference to `newSurf' 
/usr/local/lib/libGoToolsCore.a(Sphere.C.o): In function `Go::Sphere::createNonRationalSpline(double) const': 
Sphere.C:(.text+0x7b45): undefined reference to `s1302' 
Sphere.C:(.text+0x7c42): undefined reference to `freeSurf' 
/usr/local/lib/libGoToolsCore.a(Torus.C.o): In function `Go::Torus::createNonRationalSpline(double) const': 
Torus.C:(.text+0x66a7): undefined reference to `s1302' 
Torus.C:(.text+0x67a4): undefined reference to `freeSurf' 
/usr/local/lib/libGoToolsCore.a(intersect2Dcurves.C.o): In function `Go::intersectCurvePoint(Go::ParamCurve const*, Go::Point, double, std::vector<double, std::allocator<double> >&, std::vector<std::pair<double, double>, std::allocator<std::pair<double, double> > >&)': 
intersect2Dcurves.C:(.text+0x1a4): undefined reference to `s1871' 
intersect2Dcurves.C:(.text+0x37e): undefined reference to `freeIntcrvlist' 
intersect2Dcurves.C:(.text+0x3a6): undefined reference to `freeCurve' 
/usr/local/lib/libGoToolsCore.a(intersect2Dcurves.C.o): In function `Go::intersect2Dcurves(Go::ParamCurve const*, Go::ParamCurve const*, double, std::vector<std::pair<double, double>, std::allocator<std::pair<double, double> > >&, std::vector<int, std::allocator<int> >&, std::vector<std::pair<std::pair<double, double>, std::pair<double, double> >, std::allocator<std::pair<std::pair<double, double>, std::pair<double, double> > > >&)': 
intersect2Dcurves.C:(.text+0xb1f): undefined reference to `sh1857' 
intersect2Dcurves.C:(.text+0xf2d): undefined reference to `freeIntcrvlist' 
intersect2Dcurves.C:(.text+0xf7c): undefined reference to `freeCurve' 
intersect2Dcurves.C:(.text+0xf95): undefined reference to `freeCurve' 
/usr/local/lib/libGoToolsCore.a(intersectCurveSurf.C.o): In function `Go::intersectCurveSurf(Go::SplineCurve*, Go::SplineSurface*, double, std::vector<std::pair<double, Go::Point>, std::allocator<std::pair<double, Go::Point> > >&, std::vector<int, std::allocator<int> >&, std::vector<std::pair<std::pair<double, Go::Point>, std::pair<double, Go::Point> >, std::allocator<std::pair<std::pair<double, Go::Point>, std::pair<double, Go::Point> > > >&)': 
intersectCurveSurf.C:(.text+0x320): undefined reference to `sh1858' 
intersectCurveSurf.C:(.text+0x801): undefined reference to `freeIntcrvlist' 
intersectCurveSurf.C:(.text+0x850): undefined reference to `freeSurf' 
intersectCurveSurf.C:(.text+0x869): undefined reference to `freeCurve' 
/usr/local/lib/libGoToolsCore.a(intersectcurves.C.o): In function `Go::intersectcurves(Go::SplineCurve*, Go::SplineCurve*, double, std::vector<std::pair<double, double>, std::allocator<std::pair<double, double> > >&)': 
intersectcurves.C:(.text+0x2b9): undefined reference to `sh1857' 
intersectcurves.C:(.text+0x3ff): undefined reference to `freeIntcrvlist' 
intersectcurves.C:(.text+0x451): undefined reference to `freeCurve' 
intersectcurves.C:(.text+0x464): undefined reference to `freeCurve' 
/usr/local/lib/libGoToolsCore.a(intersectcurves.C.o): In function `Go::intersectcurves(Go::SplineCurve*, Go::SplineCurve*, double, std::vector<std::pair<double, double>, std::allocator<std::pair<double, double> > >&, std::vector<std::pair<std::pair<double, double>, std::pair<double, double> >, std::allocator<std::pair<std::pair<double, double>, std::pair<double, double> > > >&)': 
intersectcurves.C:(.text+0x6d2): undefined reference to `sh1857' 
intersectcurves.C:(.text+0x97e): undefined reference to `freeIntcrvlist' 
intersectcurves.C:(.text+0x9dc): undefined reference to `freeCurve' 
intersectcurves.C:(.text+0x9ef): undefined reference to `freeCurve' 
/usr/local/lib/libGoToolsCore.a(intersectcurves.C.o): In function `Go::intersectCurvePlane(Go::ParamCurve*, Go::Point const&, Go::Point const&, double, std::vector<double, std::allocator<double> >&, std::vector<std::pair<double, double>, std::allocator<std::pair<double, double> > >&)': 
intersectcurves.C:(.text+0xb76): undefined reference to `sh1850' 
intersectcurves.C:(.text+0xd33): undefined reference to `freeIntcrvlist' 
intersectcurves.C:(.text+0xd70): undefined reference to `freeCurve' 
collect2: error: ld returned 1 exit status 
./run: line 29: -o: command not found 
Program compiled : circle 
./run: line 31: circle: command not found 

This is the reason why I was looking for a simple Makefile easy to modify to compile my own circle.C file or any other file using GoTools. 
If you would have such a Makefile, it would be great. 

Thanks a lot for any help. 
Best regards, 

Gilles 


De: "VibekeSkytt" <notifications@github.com> 
À: "SINTEF-Geometry/GoTools" <GoTools@noreply.github.com> 
Cc: "Gilles Quéméner" <quemener@lpccaen.in2p3.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 19 Août 2020 16:10:51 
Objet: Re: [SINTEF-Geometry/GoTools] Compiling a simple code (#303) 





To compile one single application file or example file you can write make application name, for instance make Circle. You must run cmake first. 

Vibeke

**Comment by GBZH** [comment]
Finally I managed to solve the compiling problem :  the order of the libraries in the g++ command had to be changed. It works fine with the following command:
g++ -std=c++11 $ofile -L/usr/local/lib -lviewlib -lGoTopology -lGoImplicitization -lparametrization -lGoTrivariate -lGoIgeslib -lGoLRspline2D -lGoIntersections -lGoCompositeModel -lGoQualityModule -lGoTrivariateModel -lGoIsogeometricModel -lGoToolsCore -lsisl -lttl -lnewmat -lstdc++ -lm -o $file
