### ISSUE TITLE
Issue on GCC > 10 due to duplicate functions

### ISSUE THREAD

**Issue by agemuend** [SINTEF-Geometry/GoTools#335]
lrsplines2D/src/TrimUtils.C and LRApproxApp.C contain two duplicate functions which leads to a compile error on GCC > 10, due to fno-common being the default now 

https://github.com/SINTEF-Geometry/GoTools/blob/master/lrsplines2D/src/TrimUtils.C#L54
https://github.com/SINTEF-Geometry/GoTools/blob/master/lrsplines2D/src/LRApproxApp.C#L368

**Comment by agemuend** [comment]
Just making the functions static in LRApproxApp.C is enough

**Comment by sbriseid** [comment]
Hi!

Thanks for the heads up and suggested fix! It has been added to the master branch.
