### ISSUE TITLE
can't build gotools because of missing CMakeLists.txt

### ISSUE THREAD

**Issue by Higarigh** [SINTEF-Geometry/GoTools#34]
Hi there,

I can't build gotools because of missing CMakeLists.txt files in sisl/ and ttl/:

```
 Boost  found.

 CMake Error at CMakeLists.txt:119 (ADD_SUBDIRECTORY):
   The source directory

     /opt/GoTools/sisl

   does not contain a CMakeLists.txt file.



 CMake Error at CMakeLists.txt:120 (ADD_SUBDIRECTORY):
   The source directory

     /opt/GoTools/ttl

   does not contain a CMakeLists.txt file.
```
Why are there no such files?

Steps to reproduce:
1. git clone https://github.com/SINTEF-Geometry/GoTools.git
2. cd GoTools/
3. mkdir build && cd build
4. ccmake ../
5. Hit "c" to configure
6. fails with the errors above

Thanks

Sincerely,
Philip

System: Red Hat 6.6

**Comment by sbriseid** [comment]
Thank you for your feedback.

Both SISL and TTL are submodules, which means that the clone command should be:
# git clone --recursive https://github.com/SINTEF-Geometry/GoTools.git
Furthermore the submodules should be initialized:
# git submodule update --init --recursive

These instructions should be part of the INSTALL file. Thank you for bringing this to my attention, I'll make sure to add them.

Sincerely,
Sverre

**Comment by Higarigh** [comment]
Thanks. Jup, I think adding these commands to INSTALL file would help many peoples.

**Comment by sbriseid** [comment]
Done.

I.e. the user must switch to the 'working' branch to get that info ... The 'master' branch will get that info in our next release.
