### ISSUE TITLE
newmat conversion

### ISSUE THREAD

**Issue by fgfuchs** [SINTEF-Geometry/GoTools#77]
The following should be fixed:

gotools-all/gotools/newmat/app/tmtd.cpp:28:51: warning: conversion to ‘RBD_COMMON::Real {aka double}’ from ‘long int’ may alter its value [-Wconversion]
    for (i=2;i<=5;i++) for (j=1;j<=20; j++) X(i,j) = (long)X(i-1,j) \* j % 1001;

gotools-all/gotools/newmat/app/tmtd.cpp:47:17: warning: conversion to ‘RBD_COMMON::Real {aka double}’ from ‘long int’ may alter its value [-Wconversion]
          Y(i,j) = (long)Y(i-1,j) \* j % 101;

gotools-all/gotools/newmat/app/tmtd.cpp:63:17: warning: conversion to ‘RBD_COMMON::Real {aka double}’ from ‘long int’ may alter its value [-Wconversion]
          X(i,j) = (long)X(i-1,j) \* j % 1001;

gotools-all/gotools/newmat/app/tmtd.cpp:75:17: warning: conversion to ‘RBD_COMMON::Real {aka double}’ from ‘long int’ may alter its value [-Wconversion]
          X(i,j) = (long)X(i-1,j) \* j % 1001;

gotools-all/gotools/newmat/app/tmtd.cpp:88:17: warning: conversion to ‘RBD_COMMON::Real {aka double}’ from ‘long int’ may alter its value [-Wconversion]
          X(i,j) = (long)X(i-1,j) \* j % 1001;

gotools-all/gotools/newmat/app/tmtd.cpp:111:31: warning: conversion to ‘RBD_COMMON::Real {aka double}’ from ‘long int’ may alter its value [-Wconversion]
       for (i=2;i<=n;i++) X(i) = (long)X(i-1) \* 31 % 1001;

**Comment by sbriseid** [comment]
We do not really care about the app.
