### ISSUE TITLE
ttl logical not

### ISSUE THREAD

**Issue by fgfuchs** [SINTEF-Geometry/GoTools#78]
The following should be fixed with more parantheses:

gotools-all/gotools/ttl/include/ttl/ttl.h:728:50: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     if (!TraitsType::orient2d(d_iter, d0, point) >= 0)

gotools-all/gotools/ttl/include/ttl/ttl.h:734:50: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     if (!TraitsType::orient2d(d_iter, d0, point) >= 0)

gotools-all/gotools/ttl/include/ttl/ttl.h:740:50: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     if (!TraitsType::orient2d(d_iter, d0, point) >= 0)

**Comment by sbriseid** [comment]
Fixed!
